config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      put :start_task
      put :complete_task
    end
  end
  resources :users
  resources :teams do
    resources :memberships, only: [:create, :destroy]
  end
  root 'teams#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
    include AASM
    aasm column: 'status' do
        state :pending, initial: true
        state :in_progress, :completed

        event :start do
            transitions from: :pending, to: :in_progress
            before do
                self.started_at = Time.now
            end
        end

        event :complete do
            transitions from: :in_progress, to: :completed
            before do
                self.completed_at = Time.now
            end
        end

        def may_start?
            pending?
        end
    end
    has_many :assignments
    has_many :users, through: :assignments

    validates :title, presence: true
    validates :description, presence: true
    validates :due_date, presence: true

    before_save :set_default_values

    private

    def set_default_values
        self.started_at ||= Time.now if in_progress?
        self.completed_at ||= Time.now if completed?
    end
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :memberships
    has_many :users, through: :memberships
end

app/models/user.rb
class User < ApplicationRecord
    has_many :assignments
    has_many :tasks, through: :assignments
    has_many :memberships
    has_many :teams, through: :memberships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
    before_action :set_team, only: [:create]
    before_action :set_membership, only: [:destroy]

    def create 
        @membership = @team.memberships.build(membership_params)
        if @membership.save
            redirect_to @team, notice: 'Membership was successfully created.'
        else
            redirect_to @team, alert: 'Membership was not created.'
        end
    end

    def destroy 
        @membership.destroy
        redirect_to @membership.team, notice: 'Membership was successfully destroyed.'
    end


    private

    def set_team
        @team = Team.find(params[:team_id])
    end

    def set_membership
        @membership = Membership.find(params[:id])
    end

    def membership_params
        params.require(:membership).permit(:user_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy, :start_task, :complete_task]
  
    def index
      @tasks = Task.all
    end
  
    def show
    end
  
    def new
      @task = Task.new
    end
  
    def edit
    end
  
    def create
      @task = Task.new(task_params)
  
      if @task.save
        redirect_to @task, notice: 'Tarea creada correctamente.'
      else
        render :new
      end
    end
  
    def update
      if @task.update(task_params)
        redirect_to @task, notice: 'Tarea actualizada correctamente.'
      else
        render :edit
      end
    end
  
    def destroy
      @task.destroy
      redirect_to tasks_url, notice: 'Tarea eliminada correctamente.'
    end
  
    def start_task
      @task.start! if @task.may_start?
      redirect_to @task
    end
  
    def complete_task
      @task.complete! if @task.may_complete?
      redirect_to @task
    end
  
    private
      def set_task
        @task = Task.find(params[:id])
      end
  
      def task_params
        params.require(:task).permit(:title, :description, :due_date, :status)
      end
  end  

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    before_action :set_team, only: [:show, :edit, :update, :destroy]

    def index
        @teams = Team.all
    end

    def show
        @membership = Membership.new(team: @team)
    end

    def new
        @team = Team.new
    end

    def edit
    end

    def create
        @team = Team.new(team_params)
        if @team.save
            redirect_to @team, notice: 'Team was successfully created.'
        else
            render :new
        end
    end

    def update
        if @team.update(team_params)
            redirect_to @team, notice: 'Team was successfully updated.'
        else
            render :edit
        end
    end

    def destroy
        @team.destroy
        redirect_to teams_url, notice: 'Team was successfully destroyed.'
    end

    private

    def set_team
        @team = Team.find(params[:id])
    end

    def team_params
        params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooPms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memberships/_form.html.erb
<%= form_with(model: [team, membership], url: team_memberships_path(team)) do |form| %>
  <%= form.collection_select :user_id, User.all, :id, :name %>
  <%= form.submit "Asignar Usuario" %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tareas</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= task.title %> - Estado: <%= task.status %>
      <% if task.pending? %>
        <%= link_to "Iniciar", start_task_task_path(task), method: :put, data: {confirm: 'Are you sure to start this task?'} %>
      <% elsif task.in_progress? %>
        <%= link_to "Completar", complete_task_task_path(task), method: :put %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Nueva Tarea</h1>
<%= form_with model: @task, url: tasks_path do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.submit "Crear Tarea" %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p>Estado: <%= @task.status %></p>
<% if @task.in_progress? %>
  <p>Fecha de inicio: <%= @task.started_at %></p>
<% elsif @task.completed? %>
  <p>Fecha de finalización: <%= @task.completed_at %></p>
<% end %>